### ISSUE TITLE
Not working chat gpt lmao api

### ISSUE THREAD

**Issue by vpsbykaif** [F33RNI/GPT-Telegramus#146]
I have copy the json from the extension as per the instruction but it still not working

![Screenshot_20240309_195829_Telegram](https://github.com/F33RNI/GPT-Telegramus/assets/149788775/b6032a42-a97d-4061-a777-1a3c382f8da9)

**Comment by F33RNI** [comment]
Please provide logs

**Comment by F33RNI** [comment]
> from session not created: This version of ChromeDriver only supports Chrome version 122 Current browser version is 118.0.5993.117 
>

Please read your logs. You need to update Chrome

**Comment by alfsoft** [comment]
I'm posting here just to not start a new issue. When running the latest version inside a docker that was set up according to [this guide](https://github.com/F33RNI/GPT-Telegramus?tab=readme-ov-file#from-github-package) and asking ChatGPT about something , I get this error in a log:
```
[2024-03-10 14:27:21] [205    ] [ERROR  ] Error processing request
Traceback (most recent call last):
  File "request_processor.py", line 104, in request_processor
  File "module_wrapper_global.py", line 223, in process_request
Exception: lmao_chatgpt process is not running
[2024-03-10 14:27:21] [6      ] [INFO   ] Setting prevent_shutdown_flag
[2024-03-10 14:27:21] [6      ] [INFO   ] Trying to kill lmao_chatgpt process with PID 205
[2024-03-10 14:27:22] [6      ] [INFO   ] Killed? True
[2024-03-10 14:27:22] [6      ] [INFO   ] Container with ID 1908173171 (PID 205) was removed from the queue
[2024-03-10 14:27:26] [6      ] [INFO   ] Clearing prevent_shutdown_flag
```

When I select a ChatGPT module I get only this in a log (no word about lmao_process as mentioned by others):
```
[2024-03-10 14:40:52] [6      ] [INFO   ] Reading users database from /app/config/users.json
[2024-03-10 14:40:52] [6      ] [INFO   ] Reading users database from /app/config/users.json
[2024-03-10 14:40:52] [6      ] [INFO   ] Saving users database to /app/config/users.json
[2024-03-10 14:40:52] [6      ] [INFO   ] Reading users database from /app/config/users.json
[2024-03-10 14:40:52] [6      ] [INFO   ] Saving users database to /app/config/users.json
[2024-03-10 14:40:52] [6      ] [INFO   ] module markup action from Xxx (xxxxxxxxx)
[2024-03-10 14:40:56] [6      ] [INFO   ] Reading users database from /app/config/users.json
[2024-03-10 14:40:56] [6      ] [INFO   ] Reading users database from /app/config/users.json
[2024-03-10 14:40:56] [6      ] [INFO   ] Saving users database to /app/config/users.json
[2024-03-10 14:40:56] [6      ] [INFO   ] Reading users database from /app/config/users.json
[2024-03-10 14:40:56] [6      ] [INFO   ] Saving users database to /app/config/users.json
[2024-03-10 14:40:56] [6      ] [INFO   ] module markup action from Xxx (xxxxxxxxx)
[2024-03-10 14:40:56] [6      ] [INFO   ] Reading users database from /app/config/users.json
[2024-03-10 14:40:56] [6      ] [INFO   ] Saving users database to /app/config/users.json
[2024-03-10 14:40:56] [6      ] [INFO   ] Reading users database from /app/config/users.json
[2024-03-10 14:40:56] [6      ] [INFO   ] Reading users database from /app/config/users.json
```

The module was configured by instructions from lmao_chatgpt.json

**Comment by vpsbykaif** [comment]
I have to host the lmao api please explain me that.

**Comment by F33RNI** [comment]
Сlosing this issue because it has nothing to do with GPT-Telegramus

**Comment by F33RNI** [comment]
https://github.com/F33RNI/LlM-Api-Open/commit/71a04f84a07653844e8060a600ccc4cd63935085

**Comment by F33RNI** [comment]
I'll post a release soon

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/148

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/148

**Comment by F33RNI** [comment]
Please check config in new release

**Comment by F33RNI** [comment]
> chatgpt initialization error

disable headless mode and see if u get ChatGPT page loaded

**Comment by F33RNI** [comment]
Refresh your cookies

**Comment by F33RNI** [comment]
I don't have a paid account (or the desire to buy one), so I can't test the official API. Also, i don’t have much time for this project due to my studies...
