### ISSUE TITLE
[ERROR  ] Initialization error

### ISSUE THREAD

**Issue by ilya-88** [F33RNI/GPT-Telegramus#162]
Hello, I can't figure out what I'm doing wrong

2024-05-01 22:08:31 [2024-05-01 19:08:31] [7      ] [INFO   ] GPT-Telegramus version: 5.4.2
2024-05-01 22:08:31 [2024-05-01 19:08:31] [7      ] [INFO   ] https://github.com/F33RNI/GPT-Telegramus
2024-05-01 22:08:31 [2024-05-01 19:08:31] [7      ] [INFO   ] Loading config file /app/config.json
2024-05-01 22:08:31 [2024-05-01 19:08:31] [7      ] [INFO   ] Enabled modules: lmao_chatgpt, lmao_ms_copilot, gemini, groq
2024-05-01 22:08:31 [2024-05-01 19:08:31] [7      ] [INFO   ] Parsing module_configs directory
2024-05-01 22:08:31 [2024-05-01 19:08:31] [7      ] [ERROR  ] Initialization error
2024-05-01 22:08:31 Traceback (most recent call last):
2024-05-01 22:08:31   File "main.py", line 142, in main
2024-05-01 22:08:31   File "main.py", line 81, in load_and_parse_config
2024-05-01 22:08:31 FileNotFoundError: [Errno 2] No such file or directory: 'module_configs'
2024-05-01 22:08:31 Traceback (most recent call last):
2024-05-01 22:08:31   File "main.py", line 235, in <module>
2024-05-01 22:08:31   File "main.py", line 219, in main
2024-05-01 22:08:31 UnboundLocalError: local variable 'queue_handler_' referenced before assignment
2024-05-01 22:08:31 [7] Failed to execute script 'main' due to unhandled exception!

**Comment by F33RNI** [comment]
You need to download [directory with config files for modules](https://github.com/F33RNI/GPT-Telegramus/tree/main/module_configs). Pls check repo

**Comment by F33RNI** [comment]
You can specify path to it in `config.json`

```json
"__comment05__": "Paths to files and directories",
"files": {
    "module_configs_dir": "module_configs",
```
