### ISSUE TITLE
error ,cannot response

### ISSUE THREAD

**Issue by skyyaman** [F33RNI/GPT-Telegramus#3]
2023-02-16 11:23:46 ERROR    No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/telegram/ext/_updater.py", line 607, in _network_loop_retry
    if not await action_cb():
  File "/usr/local/python3/lib/python3.9/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
    raise exc
  File "/usr/local/python3/lib/python3.9/site-packages/telegram/ext/_updater.py", line 320, in polling_action_cb
    updates = await self.bot.get_updates(
  File "/usr/local/python3/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 524, in get_updates
    updates = await super().get_updates(
  File "/usr/local/python3/lib/python3.9/site-packages/telegram/_bot.py", line 331, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/usr/local/python3/lib/python3.9/site-packages/telegram/_bot.py", line 3510, in get_updates
    await self._post(
  File "/usr/local/python3/lib/python3.9/site-packages/telegram/_bot.py", line 419, in _post
    return await self._do_post(
  File "/usr/local/python3/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
    return await super()._do_post(
  File "/usr/local/python3/lib/python3.9/site-packages/telegram/_bot.py", line 450, in _do_post
    return await request.post(
  File "/usr/local/python3/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 165, in post
    result = await self._request_wrapper(
  File "/usr/local/python3/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 330, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023-02-16 11:23:49 INFO     /gpt command from user min long request: hello
2023-02-16 11:23:49 INFO     Asking: hello
error: Unknown error
2023-02-16 11:23:49 ERROR    Unknown error
Traceback (most recent call last):
  File "/opt/GPT-Telegramus/AIHandler.py", line 140, in gpt_loop
    asyncio.new_event_loop().run_until_complete(chatbot_async_result())
  File "/usr/local/python3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/GPT-Telegramus/AIHandler.py", line 136, in chatbot_async_result
    async for line in self.chatbot.ask(str(container.request)):
  File "/usr/local/python3/lib/python3.9/site-packages/revChatGPT/V2.py", line 177, in ask
    raise Exception("Unknown error")
Exception: Unknown error

**Comment by F33RNI** [comment]
There have been several API updates: https://github.com/acheong08/ChatGPT

Now I am using V1. Check, please
