### ISSUE TITLE
Bot don't reacts on anything.

### ISSUE THREAD

**Issue by XamelionAG** [F33RNI/GPT-Telegramus#36]
Hello, 

I have installed the bot and configured. Then started... It's looks like there are no problems... log is ok. But nothing happens if I write to the bot...

Can you Help me, please?

**Comment by F33RNI** [comment]
Are you writing to the right bot?  (check bot's token)
If yes, pls show the logs here

**Comment by XamelionAG** [comment]
[2023-07-11 20:10:38] [258804  ] [INFO    ] Logging setup is complete for current process
[2023-07-11 20:10:38] [258804  ] [INFO    ] LoggingHandler PID: 258806
[2023-07-11 20:10:38] [258804  ] [INFO    ] GPT-Telegramus version: 3.0.3
[2023-07-11 20:10:38] [258804  ] [INFO    ] https://github.com/F33RNI/GPT-Telegramus
[2023-07-11 20:10:38] [258804  ] [INFO    ] Loading config.json
[2023-07-11 20:10:38] [258804  ] [INFO    ] Loaded json from config.json
[2023-07-11 20:10:38] [258804  ] [INFO    ] Loading messages.json
[2023-07-11 20:10:38] [258804  ] [INFO    ] Loaded json from messages.json
[2023-07-11 20:10:38] [258804  ] [INFO    ] Starting queue_processing_loop
[2023-07-11 20:10:38] [258804  ] [INFO    ] queue_processing_loop thread: Thread-1
[2023-07-11 20:10:38] [258804  ] [INFO    ] Starting telegram bot 

[2023-07-11 20:10:41] [258804  ] [INFO    ] Application started   **//here it stops after i run the main.py and then i am writing to the bot /start and nothing happens!**

[2023-07-11 20:13:39] [258804  ] [INFO    ] Application is stopping. This might take a moment. **///// here i try STRG+C to close the bot**

[2023-07-11 20:13:39] [258804  ] [ERROR   ] Telegram bot error!
Traceback (most recent call last):
  File "/home/projektxamelion/xamelionAI/GPT-Telegramus/BotHandler.py", line 518, in start_bot
    self._event_loop.run_until_complete(self._application.run_polling())
  File "/home/projektxamelion/.local/lib/python3.8/site-packages/telegram/ext/_application.py", line 752, in run_polling
    return self.__run(
  File "/home/projektxamelion/.local/lib/python3.8/site-packages/telegram/ext/_application.py", line 954, in __run
    loop.run_until_complete(self.stop())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/projektxamelion/.local/lib/python3.8/site-packages/telegram/ext/_application.py", line 634, in stop
    await self.update_queue.join()
  File "/usr/lib/python3.8/asyncio/queues.py", line 220, in join
    await self._finished.wait()
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
RuntimeError: Task <Task pending name='Task-13' coro=<Application.stop() running at /home/projektxamelion/.local/lib/python3.8/site-packages/telegram/ext/_application.py>
[2023-07-11 20:13:39] [258804  ] [INFO    ] Restarting bot polling after 30 seconds
[2023-07-11 20:13:48] [258804  ] [WARNING ] KeyboardInterrupt @ bot_start
[2023-07-11 20:13:48] [258804  ] [WARNING ] Telegram bot stopped
[2023-07-11 20:13:48] [258804  ] [WARNING ] Stopping queue_processing_loop
[2023-07-11 20:13:48] [258804  ] [WARNING ] queue_processing_loop finished
[2023-07-11 20:13:48] [258804  ] [INFO    ] GPT-Telegramus exited successfully

**Comment by XamelionAG** [comment]
i see there is no **users.json** added to repository... maybe it is it?

**Comment by F33RNI** [comment]
`users.json` is a user database file that is created "dynamically".

For now pls try to stop the bot, then write something to it, and then open the link below (replace <TOKEN> in the link with your bot's API token).  You should see your message.  If you don't see it, then it's a problem with your telegram bot token / API / etc., not with GPT-Telegramus

`https://api.telegram.org/bot<TOKEN>/getUpdates`

**Comment by XamelionAG** [comment]
I have followed your instructions.
With token is everything ok.
What can it be?

**Comment by F33RNI** [comment]
Please try running the bot on a different machine / Python version...
because I can't reproduce your problem =(

**Comment by F33RNI** [comment]
Сlosing this Issue, because neither I nor anyone else can reproduce your problem
