### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by Wellmare** [F33RNI/GPT-Telegramus#45]
```
Asking ChatGPT (API type 3)...
[2023-08-08 11:43:46] [15356   ] [INFO    ] Saving conversation 6ccc2566-faee-4371-9df7-139355eef3bb
[2023-08-08 11:43:46] [15356   ] [INFO    ] Loading users.json
[2023-08-08 11:43:46] [15356   ] [INFO    ] Loaded json from users.json
[2023-08-08 11:43:46] [15356   ] [INFO    ] Saving to users.json
[2023-08-08 11:43:46] [15356   ] [INFO    ] Response successfully processed for user Иван Колипов (1311323594)
[2023-08-08 11:43:47] [15356   ] [WARNING ] Error sending reply with escape_mode 0: Can't parse entities: character '!' is reserved and must be escaped with the preceding '\'         You can ignore this message
[2023-08-08 11:43:47] [15356   ] [INFO    ] Trying to close ChatGPT session
[2023-08-08 11:43:47] [15356   ] [INFO    ] ChatGPT module exited
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002257489C670>
Traceback (most recent call last):
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002257489C670>
Traceback (most recent call last):
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002257489C670>
Traceback (most recent call last):
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\ulyas\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[2023-08-08 11:43:47] [14292   ] [INFO    ] Trying to kill process with PID 15356
[2023-08-08 11:43:47] [14292   ] [INFO    ] Killed? True
[2023-08-08 11:43:47] [14292   ] [INFO    ] The response were written to the file: data\2023_08_08_11_43_43.log
[2023-08-08 11:43:47] [14292   ] [INFO    ] Container with id 1074532337 (PID 15356) was removed from the queue
```
I'm assuming these errors are not normal

**Comment by F33RNI** [comment]
Most likely this is due to the fact that you can not log in.  Check your ChatGPT authorization method and proxy

**Comment by F33RNI** [comment]
Pls try API type 1

**Comment by F33RNI** [comment]
Do you have any updates on this issue? If so, pls write here. If not, I'll close this issue tomorrow
