### ISSUE TITLE
Bing ImageGen Error reading bing cookies!

### ISSUE THREAD

**Issue by meteaslandev** [F33RNI/GPT-Telegramus#89]
Bing Ai chatbot is working fine but ImageGen is not. The logs say that, this error occurred due to cookies, but if the cookies were faulty, wouldn't the Bing AI chat bot also not work? 

"
2023-11-12T16:28:14.578574+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Logging setup is complete for current process
2023-11-12T16:28:14.578751+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Logging setup is complete for current process
2023-11-12T16:28:14.579576+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Loading users.json
2023-11-12T16:28:14.579600+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Loading users.json
2023-11-12T16:28:14.579907+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Loaded json from users.json
2023-11-12T16:28:14.579936+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Loaded json from users.json
2023-11-12T16:28:14.580029+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Saving to users.json
2023-11-12T16:28:14.580054+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Saving to users.json
2023-11-12T16:28:14.580722+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Loading users.json
2023-11-12T16:28:14.580749+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Loading users.json
2023-11-12T16:28:14.580891+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Loaded json from users.json
2023-11-12T16:28:14.580917+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Loaded json from users.json
2023-11-12T16:28:14.580988+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Saving to users.json
2023-11-12T16:28:14.581019+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Saving to users.json
2023-11-12T16:28:14.581440+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Initializing Bing ImageGen module with proxy # my proxy #
2023-11-12T16:28:14.581480+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [INFO    ] Initializing Bing ImageGen module with proxy # my proxy #
2023-11-12T16:28:14.581727+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [WARNING ] No EdgeGPT_cookies.json file! Returning empty json
2023-11-12T16:28:14.581752+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [WARNING ] No EdgeGPT_cookies.json file! Returning empty json
2023-11-12T16:28:14.964673+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [WARNING ] Error sending reply with escape_mode 0: Can't parse entities: 
character '!' is reserved and must be escaped with the preceding '\'     You can ignore this message
2023-11-12T16:28:14.965690+00:00 app[worker.1]: [2023-11-12 16:28:14] [167     ] [WARNING ] Error sending reply with escape_mode 0: Can't parse entities: 
character '!' is reserved and must be escaped with the preceding '\'     You can ignore this message
2023-11-12T16:28:15.488642+00:00 app[worker.1]: [2023-11-12 16:28:15] [167     ] [ERROR   ] Error processing request!
2023-11-12T16:28:15.488652+00:00 app[worker.1]: Traceback (most recent call last):
2023-11-12T16:28:15.488654+00:00 app[worker.1]: File "/app/QueueHandler.py", line 372, in _request_processor
2023-11-12T16:28:15.488655+00:00 app[worker.1]: bing_image_gen_module.initialize(proxy_)
2023-11-12T16:28:15.488655+00:00 app[worker.1]: File "/app/BingImageGenModule.py", line 100, in initialize
2023-11-12T16:28:15.488656+00:00 app[worker.1]: raise e
2023-11-12T16:28:15.488656+00:00 app[worker.1]: File "/app/BingImageGenModule.py", line 81, in initialize
2023-11-12T16:28:15.488657+00:00 app[worker.1]: raise e
2023-11-12T16:28:15.488657+00:00 app[worker.1]: File "/app/BingImageGenModule.py", line 70, in initialize
2023-11-12T16:28:15.488657+00:00 app[worker.1]: raise Exception("Error reading bing cookies!")
2023-11-12T16:28:15.488658+00:00 app[worker.1]: Exception: Error reading bing cookies!
2023-11-12T16:28:15.488687+00:00 app[worker.1]: [2023-11-12 16:28:15] [167     ] [ERROR   ] Error processing request!
2023-11-12T16:28:15.488687+00:00 app[worker.1]: Traceback (most recent call last):
2023-11-12T16:28:15.488688+00:00 app[worker.1]: File "/app/QueueHandler.py", line 372, in _request_processor
2023-11-12T16:28:15.488688+00:00 app[worker.1]: bing_image_gen_module.initialize(proxy_)
2023-11-12T16:28:15.488688+00:00 app[worker.1]: File "/app/BingImageGenModule.py", line 100, in initialize
2023-11-12T16:28:15.488688+00:00 app[worker.1]: raise e
2023-11-12T16:28:15.488688+00:00 app[worker.1]: File "/app/BingImageGenModule.py", line 81, in initialize
2023-11-12T16:28:15.488689+00:00 app[worker.1]: raise e
2023-11-12T16:28:15.488689+00:00 app[worker.1]: File "/app/BingImageGenModule.py", line 70, in initialize
2023-11-12T16:28:15.488689+00:00 app[worker.1]: raise Exception("Error reading bing cookies!")
2023-11-12T16:28:15.488689+00:00 app[worker.1]: Exception: Error reading bing cookies!
2023-11-12T16:28:15.580256+00:00 app[worker.1]: [2023-11-12 16:28:15] [2       ] [INFO    ] Trying to kill process with PID 167
2023-11-12T16:28:15.580505+00:00 app[worker.1]: [2023-11-12 16:28:15] [2       ] [INFO    ] Killed? True
2023-11-12T16:28:15.580674+00:00 app[worker.1]: [2023-11-12 16:28:15] [2       ] [INFO    ] Container with id 1502570232 (PID 167) was removed from the qu"

**Comment by F33RNI** [comment]
In order for Bing Image Gen and Bin AI to work you need cookies

**Comment by F33RNI** [comment]
Are there any other questions in this issue? If not I'll close it due to inactivity

**Comment by F33RNI** [comment]
https://github.com/F33RNI/GPT-Telegramus/pull/154
